spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/wyk232511/springcloud
          searchPaths: sp-config
          #username: your-username
          #password: your-password
#        native:
#          search-locations: classpath:/config




  rabbitmq:
    host: 192.168.244.132
    port: 5672
    username: admin
    password: admin
server:
  port: 6001

eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka

management:
  endpoints:
    web:
      exposure:
        include: bus-refresh